### ISSUE TITLE
Incompatible with ratchet 0.3

### ISSUE THREAD

**Issue by asennoussi** [JDare/ClankBundle#27]
I got this error message when I tried it with ratchet 0.3
 [UnexpectedValueException]
  $request can not be null

**Comment by Venzon** [comment]
@Sshuichi
did you find any solution? i bet fix inside bundle is needed

**Comment by asennoussi** [comment]
Yes ,  you need to wrap WsServer in an additional Ratchet\Http\HttpServer layer.

**Comment by Venzon** [comment]
@Sshuichi thx for fast reply mate
will such fix be enough for clank bundle working fine with ratchet 0.3 ?
https://github.com/Venzon/ClankBundle/commit/56b5a6f696bac6615cfc901e9a8eae06e3897fa5

do you know maybe some clank bundle fork with is still maintained?

**Comment by asennoussi** [comment]
I think it should be enough , but you should test it .
I don't know for Clank but I chose to not use it anymore .. ratchet is enough for me

**Comment by Venzon** [comment]
yeah it works, thank you again
I think i will also stop using clank bundle but need like few days to implement ratchet without it 
I dont know why but after several days webserver on clank bundle stops responding to calls - maybe new ratchet version will fix this issue

**Comment by asennoussi** [comment]
Ratcet is easier ,
If you have any problems , post them on Stackoverflow ;) cheers.
