### ISSUE TITLE
Install Bundle under Symfony v2.3.1

### ISSUE THREAD

**Issue by alexbaciu** [JDare/ClankBundle#3]
Hello,

I am trying to install this package with composer under Symfony v2.3.1 but it seems that is not working:
- Conclusion: remove symfony/symfony v2.3.1
- Conclusion: don't install symfony/symfony v2.3.1
- jdare/clank-bundle 0.1.0 requires symfony/framework-bundle >=2.1,<2.3-dev -> satisfiable by symfony/symfony[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.2, v2.2.3], symfony/framework-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.2, v2.2.3].

I saw the last modification in your composer but I'm not sure you merged them.

**Comment by alexbaciu** [comment]
Here is the entire message that I received:

 Problem 1
    - Conclusion: remove symfony/symfony v2.3.1
    - Conclusion: don't install symfony/symfony v2.3.1
    - jdare/clank-bundle 0.1.0 requires symfony/framework-bundle >=2.1,<2.3-dev -> satisfiable by symfony/symfony[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.2, v2.2.3], symfony/framework-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.2, v2.2.3].
    - jdare/clank-bundle 0.1.1 requires symfony/framework-bundle >=2.1,<2.3-dev -> satisfiable by symfony/symfony[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.2, v2.2.3], symfony/framework-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.2, v2.2.3].
    - jdare/clank-bundle 0.1.2 requires symfony/framework-bundle >=2.1,<2.3-dev -> satisfiable by symfony/symfony[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.2, v2.2.3], symfony/framework-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.2, v2.2.3].
    - jdare/clank-bundle 0.1.3 requires symfony/framework-bundle >=2.1,<2.3-dev -> satisfiable by symfony/symfony[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.2, v2.2.3], symfony/framework-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.2, v2.2.3].
    - jdare/clank-bundle 0.1.4 requires symfony/framework-bundle >=2.1,<2.3-dev -> satisfiable by symfony/symfony[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.2, v2.2.3], symfony/framework-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.2, v2.2.3].
    - jdare/clank-bundle 0.1.5 requires symfony/framework-bundle >=2.1,<2.3-dev -> satisfiable by symfony/symfony[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.2, v2.2.3], symfony/framework-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.2, v2.2.3].
    - Can only install one of: symfony/symfony[v2.3.0, v2.1.0].
    - Can only install one of: symfony/symfony[v2.3.0, v2.1.1].
    - Can only install one of: symfony/symfony[v2.3.0, v2.1.10].
    - Can only install one of: symfony/symfony[v2.3.0, v2.1.11].
    - Can only install one of: symfony/symfony[v2.3.0, v2.1.2].
    - Can only install one of: symfony/symfony[v2.3.0, v2.1.3].
    - Can only install one of: symfony/symfony[v2.3.0, v2.1.4].
    - Can only install one of: symfony/symfony[v2.3.0, v2.1.5].
    - Can only install one of: symfony/symfony[v2.3.0, v2.1.6].
    - Can only install one of: symfony/symfony[v2.3.0, v2.1.7].
    - Can only install one of: symfony/symfony[v2.3.0, v2.1.8].
    - Can only install one of: symfony/symfony[v2.3.0, v2.1.9].
    - Can only install one of: symfony/symfony[v2.3.0, v2.2.0].
    - Can only install one of: symfony/symfony[v2.3.0, v2.2.1].
    - Can only install one of: symfony/symfony[v2.3.0, v2.2.2].
    - Can only install one of: symfony/symfony[v2.3.0, v2.2.3].
    - don't install symfony/framework-bundle v2.2.0|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.2.1|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.2.2|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.2.3|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.1.0|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.1.1|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.1.10|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.1.11|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.1.2|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.1.3|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.1.4|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.1.5|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.1.6|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.1.7|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.1.8|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.1.9|don't install symfony/symfony v2.3.0
    - Installation request for symfony/symfony 2.3.\* -> satisfiable by symfony/symfony[v2.3.0, v2.3.1].
    - Installation request for jdare/clank-bundle 0.1.\* -> satisfiable by jdare/clank-bundle[0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5].

**Comment by hice3000** [comment]
Same problem here.

**Comment by vsergiu** [comment]
I got same problem for version 2.3.\* , tried with 2.3.1, 2.3.2 and 2.3.3

**Comment by andythorne** [comment]
Seems to have been fixed in https://github.com/JDare/ClankBundle/commit/f1d545df7df584adcc8b70b5e4c31554a5de6373, but you will have to pull from master.

**Comment by JDare** [comment]
Added a new release: 0.1.6 with the fix for symfony version.
